[package]
name = "bch_addr"
version = "0.1.0"
authors = ["haryu703"]
edition = "2018"

[dependencies]
cash_addr = { git = "https://github.com/haryu703/rust-cash-addr.git" }
failure = "0.1.5"

[dependencies.bs58]
version = "0.2.2"
features = ["check"]
